### ISSUE TITLE
Reintroduce docgen workflow to sweet-caramel

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/sweet-caramel#87]
The following file has been removed from the develop branch because it is causing build to show as failing. It needs to be re-integrated into sweet caramel with working documentation generation.

```
# .github/workflows/run-develop-docgen.yml
# This workflow will automatically generate documentation for develop branch

name: Contracts Docgen

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - uses: canastro/copy-file-action@master
        name: "copy env file"
        with:
          source: .env.example
          target: .env
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependency
        run: sudo apt-get install graphviz && npm i lerna -g && yarn install
      - name: Run docify
        run: lerna run --scope @popcorn/hardhat docify
      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: develop-docgen
          FOLDER: packages/hardhat/docgen/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
```
